// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuR9OneVX7LU06keZNsGE8oUrvA00149Y',
    appId: '1:308056301403:web:220dd30e180bcf1021047e',
    messagingSenderId: '308056301403',
    projectId: 'to-do-72e37',
    authDomain: 'to-do-72e37.firebaseapp.com',
    storageBucket: 'to-do-72e37.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyX5i0Vpm4IY969p8Om5nYTDzzq23XkbM',
    appId: '1:308056301403:android:6881964c928c3a5d21047e',
    messagingSenderId: '308056301403',
    projectId: 'to-do-72e37',
    storageBucket: 'to-do-72e37.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhuzfe5hgVo7lP10oqFP8h_q34QNVK6tU',
    appId: '1:308056301403:ios:28a48f4dd956c6a221047e',
    messagingSenderId: '308056301403',
    projectId: 'to-do-72e37',
    storageBucket: 'to-do-72e37.firebasestorage.app',
    iosBundleId: 'com.example.toDoApp',
  );

}